### ISSUE TITLE
Supporint CentOS 6

### ISSUE THREAD

**Issue by gcjjyy** [la9527/mdir.js#6]
OS: CentOS 6.10 Final
Node: v10.24.1
NPM: 6.14.12
Python: 2.6.6

Not installed with the below error msg

```
~/mdir   
❯ npm install mdir.js
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> lzma-native@6.0.1 install /home/gcjjyy/mdir/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[lzma-native] Success: "/home/gcjjyy/mdir/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64/lzma_native.node" is installed via remote

> node-pty-prebuilt-multiarch@0.9.0 install /home/gcjjyy/mdir/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

prebuild-install WARN install /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/gcjjyy/mdir/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node)
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 47, in <module>
    import gyp
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 11, in <module>    import argparse
ImportError: No module named argparse
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 2.6.32-754.35.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gcjjyy/mdir/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v10.24.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/gcjjyy/mdir/package.json'
npm WARN i18next-cli-language-detector@1.0.1 requires a peer of i18next@^21.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mdir No description
npm WARN mdir No repository field.
npm WARN mdir No README data
npm WARN mdir No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gcjjyy/.npm/_logs/2021-11-25T15_28_51_910Z-debug.log
```

**Comment by gcjjyy** [comment]
After installing node v12, installed successfully. But failed on node v10.
